// Code generated by command: go run main.go -out simd_gemv_amd64.s. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA cgemvPermIdx<>+0(SB)/4, $0x00000000
DATA cgemvPermIdx<>+4(SB)/4, $0x00000001
DATA cgemvPermIdx<>+8(SB)/4, $0x00000004
DATA cgemvPermIdx<>+12(SB)/4, $0x00000005
DATA cgemvPermIdx<>+16(SB)/4, $0x00000002
DATA cgemvPermIdx<>+20(SB)/4, $0x00000003
DATA cgemvPermIdx<>+24(SB)/4, $0x00000006
DATA cgemvPermIdx<>+28(SB)/4, $0x00000007
GLOBL cgemvPermIdx<>(SB), RODATA|NOPTR, $32

// func cgemvInt8AVX2(out []float32, w []int8, scale []float32, q []int16, rows int, cols int)
// Requires: AVX, AVX2
TEXT ·cgemvInt8AVX2(SB), NOSPLIT, $0-112
	MOVQ    out_base+0(FP), AX
	MOVQ    w_base+24(FP), CX
	MOVQ    scale_base+48(FP), DX
	MOVQ    q_base+72(FP), BX
	MOVQ    rows+96(FP), SI
	MOVQ    cols+104(FP), DI
	VMOVDQU cgemvPermIdx<>+0(SB), Y0
	MOVQ    DI, R8
	SHLQ    $0x03, R8
	XORQ    R9, R9

rowblock:
	CMPQ  R9, SI
	JGE   done
	VPXOR Y1, Y1, Y1
	VPXOR Y2, Y2, Y2
	MOVQ  CX, R10
	MOVQ  BX, R11
	XORQ  R12, R12
	MOVQ  DI, R13
	SUBQ  $0x0f, R13

colblock_unrolled:
	CMPQ         R12, R13
	JGE          colblock_tail
	VPMOVSXBW    (R10), Y3
	VPMOVSXBW    16(R10), Y4
	VPBROADCASTQ (R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	VPMOVSXBW    32(R10), Y3
	VPMOVSXBW    48(R10), Y4
	VPBROADCASTQ 8(R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	VPMOVSXBW    64(R10), Y3
	VPMOVSXBW    80(R10), Y4
	VPBROADCASTQ 16(R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	VPMOVSXBW    96(R10), Y3
	VPMOVSXBW    112(R10), Y4
	VPBROADCASTQ 24(R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	ADDQ         $0x80, R10
	ADDQ         $0x20, R11
	ADDQ         $0x10, R12
	JMP          colblock_unrolled

colblock_tail:
	CMPQ         R12, DI
	JGE          reduce
	VPMOVSXBW    (R10), Y3
	VPMOVSXBW    16(R10), Y4
	VPBROADCASTQ (R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	ADDQ         $0x20, R10
	ADDQ         $0x08, R11
	ADDQ         $0x04, R12
	JMP          colblock_tail

reduce:
	VPHADDD   Y2, Y1, Y1
	VPERMD    Y1, Y0, Y1
	VCVTDQ2PS Y1, Y1
	VMOVUPS   (DX), Y2
	VMULPS    Y2, Y1, Y1
	VMOVUPS   Y1, (AX)
	ADDQ      $0x20, AX
	ADDQ      $0x20, DX
	ADDQ      R8, CX
	ADDQ      $0x08, R9
	JMP       rowblock

done:
	VZEROUPPER
	RET
