// Code generated by command: go run main.go -out simd_gen_amd64.s. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA cgemvPermIdx<>+0(SB)/4, $0x00000000
DATA cgemvPermIdx<>+4(SB)/4, $0x00000001
DATA cgemvPermIdx<>+8(SB)/4, $0x00000004
DATA cgemvPermIdx<>+12(SB)/4, $0x00000005
DATA cgemvPermIdx<>+16(SB)/4, $0x00000002
DATA cgemvPermIdx<>+20(SB)/4, $0x00000003
DATA cgemvPermIdx<>+24(SB)/4, $0x00000006
DATA cgemvPermIdx<>+28(SB)/4, $0x00000007
GLOBL cgemvPermIdx<>(SB), RODATA|NOPTR, $32

// func cgemvInt8AVX2(out []float32, w []int8, scale []float32, q []int16, rows int, cols int)
// Requires: AVX, AVX2
TEXT ·cgemvInt8AVX2(SB), NOSPLIT, $0-112
	MOVQ    out_base+0(FP), AX
	MOVQ    w_base+24(FP), CX
	MOVQ    scale_base+48(FP), DX
	MOVQ    q_base+72(FP), BX
	MOVQ    rows+96(FP), SI
	MOVQ    cols+104(FP), DI
	VMOVDQU cgemvPermIdx<>+0(SB), Y0
	MOVQ    DI, R8
	SHLQ    $0x03, R8
	XORQ    R9, R9

rowblock:
	CMPQ  R9, SI
	JGE   done
	VPXOR Y1, Y1, Y1
	VPXOR Y2, Y2, Y2
	MOVQ  CX, R10
	MOVQ  BX, R11
	XORQ  R12, R12
	MOVQ  DI, R13
	SUBQ  $0x0f, R13

colblock_unrolled:
	CMPQ         R12, R13
	JGE          colblock_tail
	VPMOVSXBW    (R10), Y3
	VPMOVSXBW    16(R10), Y4
	VPBROADCASTQ (R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	VPMOVSXBW    32(R10), Y3
	VPMOVSXBW    48(R10), Y4
	VPBROADCASTQ 8(R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	VPMOVSXBW    64(R10), Y3
	VPMOVSXBW    80(R10), Y4
	VPBROADCASTQ 16(R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	VPMOVSXBW    96(R10), Y3
	VPMOVSXBW    112(R10), Y4
	VPBROADCASTQ 24(R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	ADDQ         $0x80, R10
	ADDQ         $0x20, R11
	ADDQ         $0x10, R12
	JMP          colblock_unrolled

colblock_tail:
	CMPQ         R12, DI
	JGE          reduce
	VPMOVSXBW    (R10), Y3
	VPMOVSXBW    16(R10), Y4
	VPBROADCASTQ (R11), Y5
	VPMADDWD     Y3, Y5, Y3
	VPMADDWD     Y4, Y5, Y4
	VPADDD       Y3, Y1, Y1
	VPADDD       Y4, Y2, Y2
	ADDQ         $0x20, R10
	ADDQ         $0x08, R11
	ADDQ         $0x04, R12
	JMP          colblock_tail

reduce:
	VPHADDD   Y2, Y1, Y1
	VPERMD    Y1, Y0, Y1
	VCVTDQ2PS Y1, Y1
	VMOVUPS   (DX), Y2
	VMULPS    Y2, Y1, Y1
	VMOVUPS   Y1, (AX)
	ADDQ      $0x20, AX
	ADDQ      $0x20, DX
	ADDQ      R8, CX
	ADDQ      $0x08, R9
	JMP       rowblock

done:
	VZEROUPPER
	RET

DATA bfly5SignOdd<>+0(SB)/4, $0x00000000
DATA bfly5SignOdd<>+4(SB)/4, $0x80000000
DATA bfly5SignOdd<>+8(SB)/4, $0x00000000
DATA bfly5SignOdd<>+12(SB)/4, $0x80000000
DATA bfly5SignOdd<>+16(SB)/4, $0x00000000
DATA bfly5SignOdd<>+20(SB)/4, $0x80000000
DATA bfly5SignOdd<>+24(SB)/4, $0x00000000
DATA bfly5SignOdd<>+28(SB)/4, $0x80000000
GLOBL bfly5SignOdd<>(SB), RODATA|NOPTR, $32

// func kfBfly5AVX2(f0 []cpx, f1 []cpx, f2 []cpx, f3 []cpx, f4 []cpx, t1 []cpx, t2 []cpx, t3 []cpx, t4 []cpx, y *[4]float32, blocks int)
// Requires: AVX
TEXT ·kfBfly5AVX2(SB), NOSPLIT, $0-232
	MOVQ         f0_base+0(FP), AX
	MOVQ         f1_base+24(FP), CX
	MOVQ         f2_base+48(FP), DX
	MOVQ         f3_base+72(FP), BX
	MOVQ         f4_base+96(FP), SI
	MOVQ         t1_base+120(FP), DI
	MOVQ         t2_base+144(FP), R8
	MOVQ         t3_base+168(FP), R9
	MOVQ         t4_base+192(FP), R10
	MOVQ         y+216(FP), R11
	VBROADCASTSS (R11), Y0
	VBROADCASTSS 4(R11), Y1
	VBROADCASTSS 8(R11), Y2
	VBROADCASTSS 12(R11), Y3
	MOVQ         blocks+224(FP), R11
	TESTQ        R11, R11
	JZ           done

loop:
	VMOVUPS   (AX), Y4
	VMOVUPS   (CX), Y5
	VMOVUPS   (DX), Y6
	VMOVUPS   (BX), Y7
	VMOVUPS   (SI), Y8
	VMOVUPS   (DI), Y9
	VMOVUPS   (R8), Y10
	VMOVUPS   (R9), Y11
	VMOVUPS   (R10), Y12
	VMOVSLDUP Y9, Y13
	VMOVSHDUP Y9, Y9
	VPERMILPS $0xb1, Y5, Y14
	VMULPS    Y13, Y5, Y5
	VMULPS    Y9, Y14, Y9
	VADDSUBPS Y9, Y5, Y5
	VMOVSLDUP Y10, Y9
	VMOVSHDUP Y10, Y10
	VPERMILPS $0xb1, Y6, Y13
	VMULPS    Y9, Y6, Y6
	VMULPS    Y10, Y13, Y9
	VADDSUBPS Y9, Y6, Y6
	VMOVSLDUP Y11, Y9
	VMOVSHDUP Y11, Y10
	VPERMILPS $0xb1, Y7, Y11
	VMULPS    Y9, Y7, Y7
	VMULPS    Y10, Y11, Y9
	VADDSUBPS Y9, Y7, Y7
	VMOVSLDUP Y12, Y9
	VMOVSHDUP Y12, Y10
	VPERMILPS $0xb1, Y8, Y11
	VMULPS    Y9, Y8, Y8
	VMULPS    Y10, Y11, Y9
	VADDSUBPS Y9, Y8, Y8
	VADDPS    Y8, Y5, Y9
	VSUBPS    Y8, Y5, Y5
	VADDPS    Y7, Y6, Y8
	VSUBPS    Y7, Y6, Y6
	VADDPS    Y8, Y9, Y7
	VADDPS    Y7, Y4, Y7
	VMOVUPS   Y7, (AX)
	VMULPS    Y0, Y9, Y7
	VMULPS    Y2, Y8, Y10
	VADDPS    Y10, Y7, Y11
	VADDPS    Y11, Y4, Y11
	VPERMILPS $0xb1, Y5, Y5
	VPERMILPS $0xb1, Y6, Y6
	VMULPS    Y1, Y5, Y7
	VMULPS    Y3, Y6, Y10
	VADDPS    Y10, Y7, Y7
	VXORPS    bfly5SignOdd<>+0(SB), Y7, Y7
	VSUBPS    Y7, Y11, Y10
	VADDPS    Y7, Y11, Y7
	VMOVUPS   Y10, (CX)
	VMOVUPS   Y7, (SI)
	VMULPS    Y2, Y9, Y7
	VMULPS    Y0, Y8, Y10
	VADDPS    Y10, Y7, Y8
	VADDPS    Y8, Y4, Y8
	VMULPS    Y1, Y6, Y7
	VMULPS    Y3, Y5, Y10
	VSUBPS    Y10, Y7, Y4
	VSUBPS    Y7, Y10, Y5
	VBLENDPS  $0xaa, Y5, Y4, Y4
	VADDPS    Y4, Y8, Y5
	VSUBPS    Y4, Y8, Y4
	VMOVUPS   Y5, (DX)
	VMOVUPS   Y4, (BX)
	ADDQ      $0x20, AX
	ADDQ      $0x20, CX
	ADDQ      $0x20, DX
	ADDQ      $0x20, BX
	ADDQ      $0x20, SI
	ADDQ      $0x20, DI
	ADDQ      $0x20, R8
	ADDQ      $0x20, R9
	ADDQ      $0x20, R10
	DECQ      R11
	JNZ       loop

done:
	VZEROUPPER
	RET
