//go:build amd64

package rnnoise

import "golang.org/x/sys/cpu"

// Runtime dispatch for the amd64 kernels, following the four-file idiom used by
// the sibling goamr-nb and goamr-wb modules: simd.go holds the portable generic
// kernels and the fuzz-test oracle, this file gates the assembly on CPU
// features and on length, simd_amd64.s holds the assembly, and simd_noasm.go
// covers every other architecture.
//
// Only the dense int8 GEMV is vectorised so far, because it is 2.80 M of the
// 2.88 M multiply-accumulates in a frame; see the README's performance table for
// where the rest of the time goes.

var (
	useAVX2 = cpu.X86.HasAVX2
	useFMA  = cpu.X86.HasAVX2 && cpu.X86.HasFMA
)

// cgemvInt8AVX2 is implemented in simd_amd64.s (generated by tools/avogen). It
// requires rows to be a multiple of 8 and cols a multiple of 4, which the
// 8x4-blocked weight layout guarantees for any well-formed model.
//
//go:noescape
func cgemvInt8AVX2(out []float32, w []int8, scale []float32, q []int16, rows int, cols int)

func cgemvInt8(out []float32, w []int8, scale []float32, rows, cols int, q []int16, _ []int32, _ []int8) {
	if useAVX2 && rows%8 == 0 && cols%4 == 0 && rows > 0 && cols > 0 {
		cgemvInt8AVX2(out, w, scale, q, rows, cols)
		return
	}
	cgemvInt8Generic(out, w, scale, rows, cols, q)
}

// sgemvAVX2 is implemented in simd_amd64.s. It requires rows to be a multiple
// of 8; the caller falls back otherwise.
//
//go:noescape
func sgemvAVX2(out []float32, weights []float32, rows int, cols int, colStride int, x []float32)

func sgemv(out, weights []float32, rows, cols, colStride int, x []float32) {
	// rows is 128 for conv1 and 32 for dense_out, so the fast path covers
	// both; vad_dense has a single output row and falls back, which costs
	// nothing at 1536 multiply-accumulates.
	if useAVX2 && rows%8 == 0 && rows > 0 && cols > 0 {
		sgemvAVX2(out, weights, rows, cols, colStride, x)
		return
	}
	sgemvGeneric(out, weights, rows, cols, colStride, x)
}

func sparseSgemv(out, w []float32, idx []int32, rows int, x []float32) {
	sparseSgemvGeneric(out, w, idx, rows, x)
}

// quantizeAVX2 and vecTanhAVX2 are implemented in simd_amd64.s. Each handles
// whole vector groups only and leaves the tail to its wrapper.
//
//go:noescape
func quantizeAVX2(q []int16, in []float32, bias int32)

//go:noescape
func vecTanhAVX2(y []float32, x []float32, coef *[8]float32)

//go:noescape
func vecSigmoidAVX2(y []float32, x []float32, coef *[8]float32)

func quantize(q []int16, in []float32, mode QuantMode) {
	bias := int32(0)
	if mode == QuantUnsigned {
		bias = 127
	}
	n := len(in)
	if useAVX2 && n >= 16 {
		whole := n & ^15
		quantizeAVX2(q[:whole], in[:whole], bias)
		for i := whole; i < n; i++ {
			q[i] = int16(bias + int32(floor32(.5+127*in[i])))
		}
		return
	}
	quantizeGeneric(q, in, mode)
}

func sparseCgemvInt8(out []float32, w []int8, idx []int32, scale []float32, rows, cols int, q []int16) {
	sparseCgemvInt8Generic(out, w, idx, scale, rows, cols, q)
}

func vecTanh(y, x []float32) {
	n := len(x)
	if useAVX2 && n >= 8 {
		whole := n & ^7
		vecTanhAVX2(y[:whole], x[:whole], &tanhCoefs)
		for i := whole; i < n; i++ {
			y[i] = tanhApprox(x[i])
		}
		return
	}
	vecTanhGeneric(y, x)
}

func vecSigmoid(y, x []float32) {
	n := len(x)
	if useAVX2 && n >= 8 {
		whole := n & ^7
		vecSigmoidAVX2(y[:whole], x[:whole], &tanhCoefs)
		for i := whole; i < n; i++ {
			y[i] = sigmoidApprox(x[i])
		}
		return
	}
	vecSigmoidGeneric(y, x)
}

//go:noescape
func kfBfly5AVX2(f0, f1, f2, f3, f4, t1, t2, t3, t4 []cpx, y *[4]float32, blocks int)

// bfly5Vec runs the radix-5 butterfly over blocks*4 values of u, reporting
// whether it did. It is bit-identical to the scalar loop.
func bfly5Vec(f0, f1, f2, f3, f4, t1, t2, t3, t4 []cpx, y *[4]float32, blocks int) bool {
	if !useAVX2 {
		return false
	}
	n := blocks * 4
	for _, s := range [][]cpx{f0, f1, f2, f3, f4, t1, t2, t3, t4} {
		if len(s) < n {
			return false
		}
	}
	kfBfly5AVX2(f0, f1, f2, f3, f4, t1, t2, t3, t4, y, blocks)
	return true
}
